### ISSUE TITLE
camptocamp url CSS selector

### ISSUE THREAD

**Issue by cbeauchesne** [cbeauchesne/campui#21]
```CSS
// by default, link are in normal color
a {
color:#676a6c;
}

// by default, link hover is green underlyed
a:hover {
color:#1ab394;
text-decoration: underline;
}

//and orange for c2c
a[href^="https://www.camptocamp.org"]:hover,
a[href^="https://forum.camptocamp.org"]:hover,
a.c2c:hover {
    color: #FFAA45;
}

//but in markdown, we must show what is a link
[markdown] a,
markdown a {
color:#1ab394;
}

//and what is a c2c link
[markdown] a[href^="https://www.camptocamp.org"],
[markdown] a[href^="https://forum.camptocamp.org"],
[markdown] a.c2c,
markdown a[href^="https://www.camptocamp.org"],
markdown a[href^="https://forum.camptocamp.org"],
markdown a.c2c {
    color: #FFAA45;
}

```
